# Generated by Django 5.2.4 on 2025-07-22 14:42

from django.db import migrations, models
from django.utils.timezone import now  # add this import

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
    ]
