# Generated by Django 5.2.4 on 2025-07-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jenkinscilog',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
